#pragma once

#include "Direct.Sound.EAX.hxx"

#define MAX_SOUND_EAX_PROPERTY_COUNT 27

namespace Sounds::EAX
{
    const EAXLISTENERPROPERTIES Environments[MAX_SOUND_EAX_PROPERTY_COUNT] =
    {
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAXLISTENER_DEFAULTROOMHF,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = EAXLISTENER_DEFAULTDECAYHFRATIO,
            .lReflections = EAXLISTENER_DEFAULTREFLECTIONS,
            .flReflectionsDelay = EAXLISTENER_DEFAULTREFLECTIONSDELAY,
            .lReverb = EAXLISTENER_DEFAULTREVERB,
            .flReverbDelay = EAXLISTENER_DEFAULTREVERBDELAY,
            .dwEnvironment = EAX_ENVIRONMENT_GENERIC,
            .flEnvironmentSize = EAXLISTENER_DEFAULTENVIRONMENTSIZE,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAXLISTENER_DEFAULTROOMHF,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = EAXLISTENER_DEFAULTDECAYHFRATIO,
            .lReflections = EAXLISTENER_DEFAULTREFLECTIONS,
            .flReflectionsDelay = EAXLISTENER_DEFAULTREFLECTIONSDELAY,
            .lReverb = EAXLISTENER_DEFAULTREVERB,
            .flReverbDelay = EAXLISTENER_DEFAULTREVERBDELAY,
            .dwEnvironment = EAX_ENVIRONMENT_GENERIC,
            .flEnvironmentSize = EAXLISTENER_DEFAULTENVIRONMENTSIZE,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAX_MATERIAL_STONEWALL,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 0.17f,
            .flDecayHFRatio = EAXLISTENER_MINDECAYHFRATIO,
            .lReflections = -1204,
            .flReflectionsDelay = 0.001f,
            .lReverb = 207,
            .flReverbDelay = 0.002f,
            .dwEnvironment = EAX_ENVIRONMENT_PADDEDCELL,
            .flEnvironmentSize = 1.4f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -454,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 0.4f,
            .flDecayHFRatio = EAXLISTENER_DEFAULTDECAYHFRATIO,
            .lReflections = -1646,
            .flReflectionsDelay = 0.002f,
            .lReverb = 53,
            .flReverbDelay = 0.003f,
            .dwEnvironment = EAX_ENVIRONMENT_ROOM,
            .flEnvironmentSize = 1.9f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAX_MATERIAL_CURTAIN,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = 0.54f,
            .lReflections = -370,
            .flReflectionsDelay = EAXLISTENER_DEFAULTREFLECTIONSDELAY,
            .lReverb = 1030,
            .flReverbDelay = EAXLISTENER_DEFAULTREVERBDELAY,
            .dwEnvironment = EAX_ENVIRONMENT_BATHROOM,
            .flEnvironmentSize = 1.4f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAX_MATERIAL_STONEWALL,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 0.5f,
            .flDecayHFRatio = EAXLISTENER_MINDECAYHFRATIO,
            .lReflections = -1376,
            .flReflectionsDelay = 0.003f,
            .lReverb = -1104,
            .flReverbDelay = 0.004f,
            .dwEnvironment = EAX_ENVIRONMENT_LIVINGROOM,
            .flEnvironmentSize = 2.5f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF =-300,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 2.31f,
            .flDecayHFRatio = 0.64f,
            .lReflections = -711,
            .flReflectionsDelay = 0.012f,
            .lReverb = 83,
            .flReverbDelay = 0.017f,
            .dwEnvironment = EAX_ENVIRONMENT_STONEROOM,
            .flEnvironmentSize = 11.6f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -476,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 4.32f,
            .flDecayHFRatio = 0.59f,
            .lReflections = -789,
            .flReflectionsDelay = 0.02f,
            .lReverb = -289,
            .flReverbDelay = 0.03f,
            .dwEnvironment = EAX_ENVIRONMENT_AUDITORIUM,
            .flEnvironmentSize = 21.6f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -500,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 3.92f,
            .flDecayHFRatio = 0.7f,
            .lReflections = -1230,
            .flReflectionsDelay = 0.02f,
            .lReverb = -2,
            .flReverbDelay = 0.029f,
            .dwEnvironment = EAX_ENVIRONMENT_CONCERTHALL,
            .flEnvironmentSize = 19.6f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAXLISTENER_MAXROOMHF,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 2.91f,
            .flDecayHFRatio = 1.3f,
            .lReflections = -602,
            .flReflectionsDelay = 0.015f,
            .lReverb = -302,
            .flReverbDelay = 0.022f,
            .dwEnvironment = EAX_ENVIRONMENT_CAVE,
            .flEnvironmentSize = 14.6f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENERFLAGS_REVERBDELAYSCALE | EAXLISTENERFLAGS_REVERBSCALE | EAXLISTENERFLAGS_REFLECTIONSDELAYSCALE | EAXLISTENERFLAGS_REFLECTIONSSCALE | EAXLISTENERFLAGS_DECAYTIMESCALE
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -698,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 7.24f,
            .flDecayHFRatio = 0.33f,
            .lReflections = -1166,
            .flReflectionsDelay = 0.02f,
            .lReverb = 16,
            .flReverbDelay = 0.03f,
            .dwEnvironment = EAX_ENVIRONMENT_ARENA,
            .flEnvironmentSize = 36.2f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -1000,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 10.05f,
            .flDecayHFRatio = 0.23f,
            .lReflections = -602,
            .flReflectionsDelay = 0.02f,
            .lReverb = 198,
            .flReverbDelay = 0.03f,
            .dwEnvironment = EAX_ENVIRONMENT_HANGAR,
            .flEnvironmentSize = 50.3f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAX_MATERIAL_WOODWALL,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 0.3f,
            .flDecayHFRatio = EAXLISTENER_MINDECAYHFRATIO,
            .lReflections = -1831,
            .flReflectionsDelay = 0.002f,
            .lReverb = -1630,
            .flReverbDelay = 0.03f,
            .dwEnvironment = EAX_ENVIRONMENT_CARPETEDHALLWAY,
            .flEnvironmentSize = 1.9f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -300,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = 0.59f,
            .lReflections = -1219,
            .flReflectionsDelay = EAXLISTENER_DEFAULTREFLECTIONSDELAY,
            .lReverb = 441,
            .flReverbDelay = EAXLISTENER_DEFAULTREVERBDELAY,
            .dwEnvironment = EAX_ENVIRONMENT_HALLWAY,
            .flEnvironmentSize = 1.8f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -237,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 2.7f,
            .flDecayHFRatio = 0.79f,
            .lReflections = -1214,
            .flReflectionsDelay = 0.013f,
            .lReverb = 395,
            .flReverbDelay = 0.02f,
            .dwEnvironment = EAX_ENVIRONMENT_STONECORRIDOR,
            .flEnvironmentSize = 13.5f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -270,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = 0.86f,
            .lReflections = -1204,
            .flReflectionsDelay = EAXLISTENER_DEFAULTREFLECTIONSDELAY,
            .lReverb = -4,
            .flReverbDelay = EAXLISTENER_DEFAULTREVERBDELAY,
            .dwEnvironment = EAX_ENVIRONMENT_ALLEY,
            .flEnvironmentSize = EAXLISTENER_DEFAULTENVIRONMENTSIZE,
            .flEnvironmentDiffusion = 0.3f,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -3300,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = 0.54f,
            .lReflections = -2560,
            .flReflectionsDelay = 0.162f,
            .lReverb = -229,
            .flReverbDelay = 0.088f,
            .dwEnvironment = EAX_ENVIRONMENT_FOREST,
            .flEnvironmentSize = 38.0f,
            .flEnvironmentDiffusion = 0.3f,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -800,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = 0.67f,
            .lReflections = -2273,
            .flReflectionsDelay = EAXLISTENER_DEFAULTREFLECTIONSDELAY,
            .lReverb = -1691,
            .flReverbDelay = EAXLISTENER_DEFAULTREVERBDELAY,
            .dwEnvironment = EAX_ENVIRONMENT_CITY,
            .flEnvironmentSize = EAXLISTENER_DEFAULTENVIRONMENTSIZE,
            .flEnvironmentDiffusion = 0.5f,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -2500,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = 0.21f,
            .lReflections = -2780,
            .flReflectionsDelay = EAXLISTENER_MAXREFLECTIONSDELAY,
            .lReverb = -1434,
            .flReverbDelay = EAXLISTENER_MAXREVERBDELAY,
            .dwEnvironment = EAX_ENVIRONMENT_MOUNTAINS,
            .flEnvironmentSize = EAXLISTENER_MAXENVIRONMENTSIZE,
            .flEnvironmentDiffusion = 0.27f,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENERFLAGS_REVERBDELAYSCALE | EAXLISTENERFLAGS_REVERBSCALE | EAXLISTENERFLAGS_REFLECTIONSDELAYSCALE | EAXLISTENERFLAGS_REFLECTIONSSCALE | EAXLISTENERFLAGS_DECAYTIMESCALE
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -1000,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = EAXLISTENER_DEFAULTDECAYHFRATIO,
            .lReflections = EAXLISTENER_MINREFLECTIONS,
            .flReflectionsDelay = 0.061f,
            .lReverb = 500,
            .flReverbDelay = 0.025f,
            .dwEnvironment = EAX_ENVIRONMENT_QUARRY,
            .flEnvironmentSize = 17.5f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -2000,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = 0.5f,
            .lReflections = -2466,
            .flReflectionsDelay = 0.179f,
            .lReverb = -1926,
            .flReverbDelay = EAXLISTENER_MAXREVERBDELAY,
            .dwEnvironment = EAX_ENVIRONMENT_PLAIN,
            .flEnvironmentSize = 42.5f,
            .flEnvironmentDiffusion = 0.21f,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAXLISTENER_MAXROOMHF,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 1.65f,
            .flDecayHFRatio = 1.5f,
            .lReflections = -1363,
            .flReflectionsDelay = 0.008f,
            .lReverb = -1153,
            .flReverbDelay = 0.012f,
            .dwEnvironment = EAX_ENVIRONMENT_PARKINGLOT,
            .flEnvironmentSize = 8.3f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENERFLAGS_REVERBDELAYSCALE | EAXLISTENERFLAGS_REVERBSCALE | EAXLISTENERFLAGS_REFLECTIONSDELAYSCALE | EAXLISTENERFLAGS_REFLECTIONSSCALE | EAXLISTENERFLAGS_DECAYTIMESCALE
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -1000,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 2.81f,
            .flDecayHFRatio = 0.14f,
            .lReflections = 429,
            .flReflectionsDelay = 0.014f,
            .lReverb = 1023,
            .flReverbDelay = 0.021f,
            .dwEnvironment = EAX_ENVIRONMENT_SEWERPIPE,
            .flEnvironmentSize = 1.7f,
            .flEnvironmentDiffusion = 0.8f,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAX_MATERIAL_WOODWALL,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = EAXLISTENER_DEFAULTDECAYTIME,
            .flDecayHFRatio = EAXLISTENER_MINDECAYHFRATIO,
            .lReflections = -449,
            .flReflectionsDelay = EAXLISTENER_DEFAULTREFLECTIONSDELAY,
            .lReverb = 1700,
            .flReverbDelay = EAXLISTENER_DEFAULTREVERBDELAY,
            .dwEnvironment = EAX_ENVIRONMENT_UNDERWATER,
            .flEnvironmentSize = 1.8f,
            .flEnvironmentDiffusion = EAXLISTENER_DEFAULTENVIRONMENTDIFFUSION,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENER_DEFAULTFLAGS
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = EAXLISTENER_MAXROOMHF,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 8.39f,
            .flDecayHFRatio = 1.39f,
            .lReflections = -115,
            .flReflectionsDelay = 0.002f,
            .lReverb = 985,
            .flReverbDelay = 0.03f,
            .dwEnvironment = EAX_ENVIRONMENT_DRUGGED,
            .flEnvironmentSize = 1.9f,
            .flEnvironmentDiffusion = 0.5f,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENERFLAGS_REVERBDELAYSCALE | EAXLISTENERFLAGS_REVERBSCALE | EAXLISTENERFLAGS_REFLECTIONSDELAYSCALE | EAXLISTENERFLAGS_REFLECTIONSSCALE | EAXLISTENERFLAGS_DECAYTIMESCALE
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -400,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 17.23f,
            .flDecayHFRatio = 0.56f,
            .lReflections = -1713,
            .flReflectionsDelay = 0.02f,
            .lReverb = -613,
            .flReverbDelay = 0.03f,
            .dwEnvironment = EAX_ENVIRONMENT_DIZZY,
            .flEnvironmentSize = 1.8f,
            .flEnvironmentDiffusion = 0.6f,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENERFLAGS_REVERBDELAYSCALE | EAXLISTENERFLAGS_REVERBSCALE | EAXLISTENERFLAGS_REFLECTIONSDELAYSCALE | EAXLISTENERFLAGS_REFLECTIONSSCALE | EAXLISTENERFLAGS_DECAYTIMESCALE
        },
        {
            .lRoom = EAXLISTENER_MINROOM,
            .lRoomHF = -151,
            .flRoomRolloffFactor = EAXLISTENER_DEFAULTROOMROLLOFFFACTOR,
            .flDecayTime = 7.56f,
            .flDecayHFRatio = 0.91f,
            .lReflections = -626,
            .flReflectionsDelay = 0.02f,
            .lReverb = 774,
            .flReverbDelay = 0.03f,
            .dwEnvironment = EAX_ENVIRONMENT_PSYCHOTIC,
            .flEnvironmentSize = EAXLISTENER_MINENVIRONMENTSIZE,
            .flEnvironmentDiffusion = 0.5f,
            .flAirAbsorptionHF = EAXLISTENER_DEFAULTAIRABSORPTIONHF,
            .dwFlags = EAXLISTENERFLAGS_REVERBDELAYSCALE | EAXLISTENERFLAGS_REVERBSCALE | EAXLISTENERFLAGS_REFLECTIONSDELAYSCALE | EAXLISTENERFLAGS_REFLECTIONSSCALE | EAXLISTENERFLAGS_DECAYTIMESCALE
        }
    };
}